import Head from "next/head";
import styles from "../styles/Home.module.css";
import Contacts from "../components/main/Contacts";
import Footer from "../components/main/Footer";
import Header from "../components/main/Header";
import Nav from "../components/main/Nav";
import Work from "../components/main/Work";
import Bio from "../components/main/Bio";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Header />
      <Bio />
      <Work />
      <Contacts />
      <Footer />
    </div>
  );
}
